# Autogenerated file
def render(info):
    yield """<!doctype html>
<html>
  <head>
    <meta charset=\"utf-8\">
    <link rel=\"icon\" href=\"/static/img/favicon.ico\">
    <title>Geek Farm</title>
    <link href=\"/static/css/styles.css\" rel=\"stylesheet\">
  </head>
  <body>
    """
    yield """    Platform: """
    yield str(info['platform'])
    yield """
    Version: """
    yield str(info['version'])
    yield """
 """
